name: 'TEST ACTION'
branding:
  icon: 'message-circle'  
  color: 'blue'
description: 'Comments a pull request'
inputs: 
  message:
    description: 'Message'
    required: true
  GITHUB_TOKEN:
    description: 'Github token of the repository (automatically created by Github)'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.message }}
    - ${{ inputs.GITHUB_TOKEN }}