name: 'Kevin Hello'
description: 'Simple Hello World Github Action'
author: 'kevin@kelbie.me'
inputs:
  my_input:
    description: 'input description here'
    default: 'World'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: "yellow"
  icon: "bell"  
